services:
    openfire.client:
        class: jean553\OpenfireBundle\Logic\OpenfireClient
        arguments: [%openfire_client_config%]
    openfire.service:
        class: jean553\OpenfireBundle\Services\OpenfireService
        arguments: [@openfire.client]
